<?php

function _civicrm_views_get_field_options($entity, $action, $params) {
  $result = civicrm_api($entity, $action, $params);
  $values = array();
  if (empty($result['is_error']) && !empty($result['values'])) {
    foreach($result['values'] as $ary) {
      $values[$ary['value']] = $ary['label'];
    }
  }
  return $values;
}

function _civicrm_views_get_field_database($className, $name) {
  $callable = "$className::$name";
  $values = array();
  if (is_callable($callable)) {
    $values = CRM_Event_PseudoConstant::participantStatus(NULL, NULL, 'label');
  }
  return $values;
}
