views.filter.civicrm_date:
  type: views.filter.date

views.filter_value.civicrm_date:
  type: views.filter_value.date

views.filter.civicrm_custom_option:
  type: views.filter.in_operator

views.filter_value.civicrm_custom_option:
  type: views.filter_value.in_operator

views.argument.civicrm_custom_multiple:
  type: views.argument.string
